<?php

/**
 * Data source plugin for easyLOD that generates FOAF XML for an person in a CSV
 * file. 
 */

/**
 * Required function. 
 *
 * Defines configuration settings for this plugin.
 */
function dataSourceConfig() {
  return array(
    'input_file' => 'data_sources/foaf/people.csv',
    );
}

/**
 * Required function.
 *
 * Defines the XML namespace that the elements generated by this plugin belong to.
 */
function getDataSourceNamespaces() {
  return array('xmlns:foaf' => 'http://xmlns.com/foaf/0.1/');
}

/**
 * Required function.
 *
 * Defines the 'human-readable' web page for an item.
 */
function getWebPage($identifier, $app) {
  $config = dataSourceConfig();
  list($namespace, $id) = explode(':', $identifier);
  if ($record = getCsvRecord($id)) {
    // Note: the template must be in Slim's 'templates' directory.
    $app->render('csvtemplate.html', array('metadata' => $record));
  }
  else {
    $app->halt(404, 'Resource not found');
  }
}

/**
 * Generate the RDF XML for the item.
 */ 
function getResourceData($identifier, $xml, $app) {
  $config = dataSourceConfig();
  list($namespace, $id) = explode(':', $identifier);
  if ($record = getCsvRecord($id)) {
    foreach ($record as $field => $value) {
      $xml->writeElementNS('foaf', $field, NULL, $value);
    }
    return $xml;
  }
  else {
    $app->halt(404);
  }
}

/**
 * Returns an associative array with field label => values
 * for the record with the value of $id in the 'Identifier'
 * (first) field. If there is more than one record with the
 * Identifier value of $id, the first matching one is returned.
 */
function getCsvRecord($id) {
  $config = dataSourceConfig();
  $csv_records = file($config['input_file']);
  $field_names = array_shift($csv_records);
  $field_names = str_getcsv($field_names);
  foreach ($csv_records as $csv_record) {
    $field_values = str_getcsv($csv_record);
    // Identifier is the first field in the CSV data.
    if ($field_values[0] == $id) {
      return array_combine($field_names, $field_values);
    }
  }
  // If none match, return FALSE.
  return FALSE;
}

