<?php

/**
 * Data source plugin for easyLOD that generates FOAF XML from 
 * a CSV file.
 */

/**
 * Required function. 
 *
 * Defines configuration settings for this plugin.
 */
function dataSourceConfig($namespace) {
  // First check to see if this configration is being
  // overridden in plugins.php.
  global $plugins;
  if (array_key_exists($namespace, $plugins)) {
    return $plugins[$namespace]['dataSourceConfig'];
  }
  // If the configuration is not being overridden, use
  // this one.
  else {
    return array(
      'input_file' => 'data_sources/foaf/people.csv',
    );
  }
}

/**
 * Required function.
 *
 * Defines the XML namespace that the elements generated by 
 * this plugin belong to.
 */
function getDataSourceNamespaces() {
  return array('xmlns:foaf' => 'http://xmlns.com/foaf/0.1/');
}

/**
 * Required function.
 *
 * Defines the 'human-readable' web page for an item.
 */
function getWebPage($identifier, $app) {
  list($namespace, $id) = explode(':', $identifier);
  $config = dataSourceConfig($namespace);
  if ($record = getCsvRecord($namespace, $id)) {
    // Note: the template must be in Slim's 'templates' directory.
    $app->render('csvtemplate.html', array('metadata' => $record));
  }
  else {
    $app->halt(404, 'Resource not found');
  }
}

/**
 * Required function.
 *
 * Generate the RDF XML for the item.
 */ 
function getResourceData($identifier, $xml, $app) {
  list($namespace, $id) = explode(':', $identifier);
  $config = dataSourceConfig($namespace);
  // Find the record identified by $id and wrap its values
  // in faof: namespaced XML markup.
  if ($record = getCsvRecord($namespace, $id)) {
    foreach ($record as $field => $value) {
      $xml->writeElementNS('foaf', $field, NULL, $value);
    }
    return $xml;
  }
  else {
    $app->halt(404);
  }
}

/**
 * Returns an associative array with field label => values
 * for the record with the value of $id in the 'Identifier'
 * (first) field. If there is more than one record with the
 * Identifier value of $id, the first matching one is returned.
 */
function getCsvRecord($namespace, $id) {
  $config = dataSourceConfig($namespace);
  $csv_records = file($config['input_file']);
  $field_names = array_shift($csv_records);
  $field_names = str_getcsv($field_names);
  // Loop through the lines in the file until we find the one
  // with the value of $id in its first column.
  foreach ($csv_records as $csv_record) {
    $field_values = str_getcsv($csv_record);
    // Identifier is the first field in the CSV data.
    if ($field_values[0] == $id) {
      return array_combine($field_names, $field_values);
    }
  }
  // If none match, return FALSE.
  return FALSE;
}

