<?php

/**
 * Data source plugin for easyLOD that gets the MODS XML from an Institutional
 * Repository (in this case, an Islandora IR). Islandora exposes full MODS
 * docuements, so this plugin simply wraps the MODS in RDF.
 */

/**
 * Required function. 
 *
 * Defines configuration settings for this plugin.
 */
function dataSourceConfig() {
  return array(
    // The base URL of the repository's MODs URLs.
    'data_base_url' => 'http://www.islandorarepo.ca/download_ds/',
    // The base URL of the repository's website.
    'web_base_url' => 'http://www.islandorarepo.ca/fedora/repository/',
  );
}

/**
 * Required function.
 *
 * Defines the XML namespace that the elements generated by this plugin belong to.
 * In the case of an Islandora IR, the XML retrieved from Islandora already has 
 * xmlns attributes so we don't need to add any additional ones.
 */
function getDataSourceNamespaces() {
  return array();
}

/**
 * Required function.
 *
 * Defines the 'human-readable' web page for an item.
 */
function getWebPage($identifier, $app) {
  $config = dataSourceConfig();
  list($namespace, $fedora_ns, $fedora_autoincrement) = explode(':', $identifier);
  $url = $config['web_base_url'] . $fedora_ns. ':' . $fedora_autoincrement;
  $app->redirect($url, 303);
}

/**
 * Required function.
 *
 * Retrieve the MODS XML for the item and insert it into the 
 * RDF XML.
 */ 
function getResourceData($identifier, $xml, $app) {
  list($namespace, $fedora_ns, $fedora_autoincrement) = explode(':', $identifier);
  $config = dataSourceConfig();
  $data_url = $config['data_base_url'] . $fedora_ns . ':' . $fedora_autoincrement . '/MODS';
  if ($mods_xml = file_get_contents($data_url)) {
    // We have the MODS XML, so all we need to do is insert it into the RDF XML.
    $xml->writeRaw($mods_xml);
    return $xml;
  }
  else {
    $app->halt(404);
  }
}

